"""Etapes 1-3 : feature engineering."""

# TODO: add_temporal_features(df) -> year, month, season...
# TODO: add_route_features(df) -> route, taux de ponctualite, taux d'annulation...
# TODO: delay_category(series) -> categories de retard
